name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install .
        pip install black flake8 pytest
    - name: Check code style with Black
      run: |
        black -l 120 --check metro tests
    - name: Lint with Flake8
      run: |
        flake8 --max-line-length=120 --ignore=E203,W503,ANN002,ANN003,ANN101,ANN102
    - name: Test with pytest
      run: |
        pytest -v
